name: Deploy to website

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  HTML-Tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Requried will all actions
    
    - name: ftp-action
      # You may pin to the exact commit or the version.
      # uses: sebastianpopp/ftp-action@eb75c5cb29d23ee4a729720a27dfb66403cb0f6d
      uses: sebastianpopp/ftp-action@v2.0.0
      with:
        # FTP host
        host: ${{ secrets.FTP_SERVER }}
        # FTP user
        user: ${{ secrets.FTP_USERNAME }}
        # FTP password
        password: ${{ secrets.FTP_PASSWORD }}
