name: Deploy to website

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]


jobs:
  Deploy-Website:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 # Requried will all actions

        
    - name: FTP Deploy
  # You may pin to the exact commit or the version.
  # uses: SamKirkland/FTP-Deploy-Action@65c6a8f943bbf04faf9b59520a103318b418952e
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        # ftp server
        server: ${{ secrets.FTP_SERVER }}
        # ftp username
        username: ${{ secrets.FTP_USERNAME }}
        # ftp password
        password: ${{ secrets.FTP_PASSWORD }}
        # Server port to connect to (read your web hosts docs)
        port: 21
        # protocol to deploy with - ftp, ftps, or ftps-legacy
        protocol: ftp
        # Folder to upload from, must end with trailing slash /
        server-dir: christoffer/
